version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=ncms
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
  web:
    build:
      context: ./
    command:
      - ./wait-for-it.sh
      - db:3306
      - --
      - python
      - ncms.py
      - --debug=False
      - --db_host=db
      - --db_password=123456
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "9000:9000"