version: '2'
services:
  web:
    scale: 2
    start_on_create: true
  bloglb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: lujiejie.me
        priority: 1
        protocol: http
        service: web
        source_port: 80
        target_port: 9000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  db:
    scale: 1
    start_on_create: true
